name = "Compose"
license = "MIT"
licenselink = "https://github.com/testnx/compose/blob/master/LICENSE"
description = "A hugo theme for documentation sites. It's inspired by forestry.io's docs page"
homepage = "https://testnx.tech"
tags = ["dark mode", "docs", "dark", "blog", "search", "documentation"]
features = ["dark mode", "docs", "dark", "blog", "search", "documentation"]

min_version = "0.76.0"

[author]
  name = "Mike"
  homepage = "https://github.com/testnx"
